### ISSUE TITLE
gVim on Windows 7/64bit

### ISSUE THREAD

**Issue by StanAngeloff** [xolox/vim-shell#1]
Hey Peter,

Great work on all Vim plug-ins, really enjoying **vim-session** and **vim-easytags**. I have an issue with **shell.dll** from **vim-shell** on Windows 7 and the 64-bit build of Vim from Google Code. I am not sure how exactly to debug it and I've tried everything I can think of (with my limited Vimscript abilities). All I get to is a very cryptic message: `E364: Library call failed`. I imagine it could be caused by the 32-bit nature of the DLL and Vim being entirely 64-bit?

Have you tried the .dll on 64-bit installs (not just 64-bit OS, but rather 64-bit Vim)? I could try installing the Windows SDK and re-compiling the DLL to target x64, but before I go ahead and do that I wanted to pick your brain.

**Comment by xolox** [comment]
Thanks Stan for reporting this issue and helping me test the new version. I've just pushed 669a9f2d5cce67b34599dc820abb471b2faeee2b which fixes the problem. I've also uploaded a new release to [Vim Online](http://www.vim.org/scripts/script.php?script_id=3123) (but then you already have the changes ;-)). Closing this issue now.
