### ISSUE TITLE
Option for WS_EX_TOPMOST

### ISSUE THREAD

**Issue by terminatorul** [xolox/vim-shell#10]
Is it possible to add an option so that :Fullscreen command will not make the maximized Vim window stay "allways on top" ?

It would be nice to be able to Alt+Tab to other windows, even if my Vim window is in full-screen mode.

I believe this should also solve issue #9 Open&Fullscreen focus

**Comment by xolox** [comment]
In the latest version WS_EX_TOPMOST can now be disabled using the [g:shell_fullscreen_always_on_top](http://peterodding.com/code/vim/shell/#shell_fullscreen_always_on_top_option) option but Alt-Tab does not work for me. Please try it out and let me know whether this works for you.

**Comment by xolox** [comment]
After taking another look at the code and my changes from yesterday I found an additional change that was required to disable the always on top behavior on Windows. I've just released `vim-shell` version 0.11.2 which should work as you want it to, assuming you've changed [g:shell_fullscreen_always_on_top](http://peterodding.com/code/vim/shell/#shell_fullscreen_always_on_top_option) from its default.

I'm closing this issue now as the problem should be resolved. If not then feel free to reopen this issue. Thanks for the feedback!
