### ISSUE TITLE
Lots of Errors after merge

### ISSUE THREAD

**Issue by oblitum** [xolox/vim-shell#12]
Commit 49bd3bfd8fe46d47117ba1f356e8ba13a178d930 (Merge branch 'master' into dev) turned the plugin unusable for me. Currently I'm using previous commit (I've `git bisect` the offending commit).

Here's the error log when trying `:Fullscreen` (sorry, I tried hard to disable VIM translation, didn't find how):

```
Erro detectado ao processar /home/francisco/.vim/addons/github-xolox-vim-shell/autoload/xolox/shell.vim:
linha  348:
E117: Função desconhecida: xolox#misc#os#is_win
E15: Expressão inválida: xolox#misc#os#is_win()
Erro detectado ao processar function xolox#shell#fullscreen:
linha    7:
E117: Função desconhecida: xolox#misc#os#is_win
E15: Expressão inválida: xolox#misc#os#is_win()
Erro detectado ao processar function xolox#shell#fullscreen..xolox#shell#maximize:
linha    7:
E117: Função desconhecida: xolox#misc#option#get
E15: Expressão inválida: xolox#misc#option#get('shell_fullscreen_items', 'mTe')
linha    8:
E121: Variável indefinida: fullscreen_items
E116: Argumentos inválidos para a função split(fullscreen_items, '.\zs')
E15: Expressão inválida: split(fullscreen_items, '.\zs')
linha   14:
E121: Variável indefinida: fullscreen_items
E15: Expressão inválida: fullscreen_items =~# 'e' && &stal != 0
Erro detectado ao processar function xolox#shell#fullscreen:
linha   47:
E117: Função desconhecida: xolox#misc#msg#warn
```

In truth, errors start to happen all the time, not just when executing vim-shell commands.

**Comment by xolox** [comment]
[From the readme](https://github.com/xolox/vim-shell#installation):

> _Please note that the vim-shell plug-in requires my vim-misc plug-in which is separately distributed._

[From the vim-misc readme](https://github.com/xolox/vim-misc#miscellaneous-auto-load-vim-scripts):

> The vim-misc plug-in contains Vim scripts that are used by most of the Vim plug-ins I've written yet don't really belong with any single one of the plug-ins. Basically it's an extended standard library of Vim script functions that I wrote during the development of my Vim profile and plug-ins.
> 
> **In the past these scripts were bundled with each plug-in, however that turned out to be a maintenance nightmare for me. That's why the miscellaneous scripts are now a proper plug-in with their own page on Vim Online.**
> 
> **Because the miscellaneous scripts are no longer bundled with my Vim plug-ins, users are now required to install the miscellaneous scripts separately**. This is unfortunate for users who are upgrading from a previous release that did bundle the miscellaneous scripts, but I don't see any way around this. Sorry!

So please install [xolox/vim-misc](https://github.com/xolox/vim-misc) as a separate plug-in and it should work.
