### ISSUE TITLE
Duplicate helptag warning for 'xolox#misc#os#exec()'.

### ISSUE THREAD

**Issue by mudox** [xolox/vim-shell#20]
I am using both of your plugins **vim-shell** and **vim-misc**, great work!

You put the help text of 'xolox#misc#os#exec()' both in _vim-shell/doc/shell.txt_ and _vim-misc/doc/misc.txt_, which will incur 'neobundle' to complain of 'duplicated helptags', becuase the **neobundle**, I guess, adopts a strategy that is to collect all plugins' doc files under its charge to a centralized place (i.e. _.vim/neobundle/.neobundle/doc_) for sake of performance.

**Comment by xolox** [comment]
Thanks for the bug report. This is now fixed, so I'm closing this issue. Happy Vimming!

**Comment by mudox** [comment]
Thanks for your response.
I'm glad to hear that.
