### ISSUE TITLE
how do you use vim-shell ? Practice, suggestions ?

### ISSUE THREAD

**Issue by goballooning** [xolox/vim-shell#21]
Hi, 

Thanks for creating this convenient vim plugin!

I'm trying to switch to `vim-shell`  from `vim-conque`.

In `vim-conque`., I normally visual select text and transfer and run them into a `Python` or `Scheme` shell with a shortcut `<F9>`. 

In the documentation of `vim-shell`, I noticed `VimShellSendString` and `VimShellSendBuffer`. 
Then I should create a shortcut with `VimShellSendString` to send text to a shell, right ?

How do you configure and use `vim-shell`  ?

Thanks in advance.
Hongying

**Comment by xolox** [comment]
I have never seen or heard of `VimShellSendString` nor `VimShellSendBuffer`, so I guess you're confusing two plug-ins which apparently (and unfortunately) share the same name.

**Comment by goballooning** [comment]
Really sorry, I did make a mistake.

Hongying.
