### ISSUE TITLE
get silent

### ISSUE THREAD

**Issue by oblitum** [xolox/vim-shell#26]
Is there an option to avoid messages being displayed when going to fullscreen, when I go to fullscreen there's a long message which I'd prefer to avoid if possible.

**Comment by xolox** [comment]
There wasn't an option, but I just added it. If you update to the latest version of vim-shell and you add the following to your vimrc the message will be gone:

``` vim
:let g:shell_fullscreen_message = 0
```

Thanks for the feedback & happy Vimming!

**Comment by oblitum** [comment]
Thanks! (late)
