### ISSUE TITLE
install on Windows question

### ISSUE THREAD

**Issue by wolfv6** [xolox/vim-shell#27]
I use Vim to write prose and notes;  Opening links from markdown files is a huge convenience.
So I installed vim-shell on Windows 7 with Vundle and Vim 7.4.
But vim-shell is not working.  Maybe I did something wrong on the install.

This is in my _vimrc file:
    Plugin 'file:///C:/Users/wolf/vimfiles/vim-misc/autoload/xolox/misc.vim'
    Plugin 'file:///C:/Users/wolf/vimfiles/shell/autoload/xolox/shell.vim'

This is my directory:
![vim-shell](https://cloud.githubusercontent.com/assets/1121166/3276565/b8f7d16c-f34c-11e3-8c80-2a3368a6b5ee.png)

Do I have it set up right?
Thank you.

**Comment by wolfv6** [comment]
The paths should contain "vim-" (not ".vim").
With the following code in my vimrc worked:

```
    " vim-misc from https://github.com/xolox/vim-misc    Vim scripts used by vim-shell
    Plugin 'xolox/vim-misc'
    call vundle#config#require(g:bundles)

    " vim-shell from https://github.com/xolox/vim-shell      <F6> opens links in browser
    Plugin 'xolox/vim-shell'
    call vundle#config#require(g:bundles)
```

Vundle installed the files to vimfiles\bundle:
![vimfiles](https://cloud.githubusercontent.com/assets/1121166/3325440/d9720214-f78e-11e3-9e5f-f475671e1773.png)

**Comment by xolox** [comment]
I corresponded with @wolfv6 via e-mail and got things sorted out, so I'm closing this issue now (only 99 issues left for me to resolve over all my repositories, I'm slowly making progress :-)).
