### ISSUE TITLE
File name expansion does not work with MakeWithShell

### ISSUE THREAD

**Issue by howsiwei** [xolox/vim-shell#29]
I have the following line in my c.vim.

``` vim
set makeprg=make\ %:r
```

So when I type make at vim command line when editting _filename.c_, it will run make _filename_.
This does not with MakeWithShell though. I know I can change it to

``` vim
let &l:makeprg = 'make '.expand('%:r')
```

but the first configuration is just more elegant.

**Comment by xolox** [comment]
To be honest I would rather remove `MakeWithShell` from the vim-shell plug-in than continue down the path of re-implementing Vim features to shoe horn something into Vim that was never meant to be :-). I'm sorry but I won't extend `MakeWithShell` further unless I can find a generic mechanism that doesn't require defining alternatives to dozens of Vim built-in commands and having to re-implement logic that is already available in Vim. I invested quite a bit of time in finding such a generic mechanism already (and the silly thing is I've hardly used Microsoft Windows in the past 6 years) so don't hold your breath :-(
