### ISSUE TITLE
Can <F6> open the vim files in the current window?

### ISSUE THREAD

**Issue by wolfv6** [xolox/vim-shell#33]
I use vim-shell <F6> to open links to other vim files.
<F6> opens the vim files in a new instance of Vim.
Is there a way to make <F6> open the vim files in the current window?
I am using vim 7.4 on Linux.

Thank you for writing vim-shell, the fastest way to open links.

**Comment by xolox** [comment]
Is there a specific reason you can't just type [gf](http://vimdoc.sourceforge.net/htmldoc/editing.html#gf) (mnemonic: "goto file") in normal mode?

There's also `Control-W Control-F` for opening the file in a new split window.

I can give a more detailed answer explaining how this won't work like you'd expect it to, however that assumes you already know about `gf`, so I thought I should ask first :-).

**Comment by wolfv6** [comment]
Thanks for telling me about gf, that works fine.
